title: Zachary Smith # your name (or website title) here
logo: "/images/Smith_Headshot_2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello! I'm a data and real estate reporter currently at <a href="https://www.crainscleveland.com/author/zachary-smith">Crain's Cleveland Business.</a> Craig Newmark Graduate School of Journalism alum. 
  <br><br>
  Previously â€” <a href="<a href="https://www.cleveland.com/staff/zsmith/posts.html">Cleveland.com</a>. ">Food Bank News</a>. Will write for money.  
  <br><br>
  <a href = "mailto: zms3516@gmail.com">Email Me!</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/zackms/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
